#!/usr/bin/env zsh

# Create a new directory and enter it
function mkcd() {
	# Check if no arguments are provided
	if [[ -z "$1" ]]; then
		echo "Usage: mkcd <directory_name>"
		echo "Error: No directory name provided."
		return 1
	fi

	# Check if more than one argument is provided
	if [[ "$#" -gt 1 ]]; then
		echo "Usage: mkcd <directory_name>"
		echo "Error: Too many arguments. Please provide only one directory name."
		return 1
	fi

	local target_dir="$1"

	# Check if the directory already exists
	if [[ -d "$target_dir" ]]; then
		echo "Directory '$target_dir' already exists. Changing into it."
		if cd "$target_dir"; then
			echo "Successfully changed to: $(pwd)"
			return 0
		else
			echo "Error: Could not change to directory '$target_dir' (permissions issue?)."
			return 1
		fi
	fi

	# Attempt to create the directory and then change into it
	if mkdir -p "$target_dir" && cd "$target_dir"; then
		echo "Successfully created and changed to: $(pwd)"
	else
		echo "Error: Could not create or change to directory '$target_dir'."
		return 1
	fi
}


# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/cp
# cp function that uses rsync
# The enabled options for rsync are:
#     -p: preserves permissions.
#     -o: preserves owner.
#     -g: preserves group.
#     -b: make a backup of the original file instead of overwriting it, if it exists.
#     -r: recurse directories.
#     -hhh: outputs numbers in human-readable format, in units of 1024 (K, M, G, T).
#     --backup-dir="/tmp/rsync-$USERNAME": move backup copies to "/tmp/rsync-$USERNAME".
#     -e /dev/null: only work on local files (disable remote shells).
#     --progress: display progress.
cpv() {
    rsync -pogbr -hhh --backup-dir="/tmp/rsync-${USERNAME}" -e /dev/null --progress "$@"
}
compdef _files cpv


# Determine size of a file or total size of a directory
function fs() {
	if du -b /dev/null >/dev/null 2>&1; then
		local arg=-sbh
	else
		local arg=-sh
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@"
	else
		du $arg .[^.]* ./*
	fi
}

# git add, commit
function gac() {
	local message="$1"

	if [[ -n "$message" ]]; then
		git add .
		git commit -S -m "$message"
	else
		echo "Error: Commit message is not provided"
		echo "Usage: gac \"Your commit message here\""
	fi
}

# git add, commit, push
function gacp() {
	local message="$1"
	local currBranch=$(git symbolic-ref --short -q HEAD)

	if [[ -n "$message" ]]; then
		git add -A
		git commit -S -m "$message"
		git push origin "$currBranch"
	else
		echo "Error: Commit message is not provided"
		echo "Usage: gacp \"Your commit message here\""
	fi
}
