#!/usr/bin/env zsh

# --- Path Exports ---

# prepend a directory to PATH if it exists
prepend_path() {
	if [[ -d "$1" ]]; then
		export PATH="$1:${PATH}"
	fi
}

typeset -U PATH # ensure entries are unique

# --- Custom Tool ---

# Various tools
prepend_path "${HOME}/.local/bin"

# GCC
prepend_path "${HOME}/opt/gcc-trunk/bin"

# Clang
prepend_path "${HOME}/opt/clang-trunk/bin"
prepend_path "${HOME}/opt/clang-p2996/bin"

# llamacpp
prepend_path "${HOME}/opt/llamacpp/bin"

unset -f prepend_path
