#!/usr/bin/env zsh
# aliases
################
if [[ -n "${__ALIASES_INCLUDED__:-}" ]]; then
	return 0
fi
readonly __ALIASES_INCLUDED__=1
################
# utility
alias ez='exec zsh'                       # restart zsh shell
alias paths='echo $PATH | tr -s ":" "\n"' # print $PATH newline separated
alias sudo='sudo '                        # Enable aliases to be sudo’ed

# Navigation
alias ..='cd ..'             # back 1 directory
alias ...='cd ../..'         # back 2
alias ....='cd ../../..'     # 3
alias .....='cd ../../../..' # 4
alias -- -='cd -'            # revert directories
alias H='cd ~'
alias dots='cd ~/dotfiles'
alias dev='cd ~/opt'
alias star='cd ~/repos/risingstarfish'

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# clang-tools-extra
alias fmt='clang-format -i *.cpp *.hpp *.h'
alias tidy='clang-tidy -i *.cpp *.hpp *.h'

alias shellcheck='shellcheck --color=always -a -x'

if [[ -n "$ZSH_VERSION" ]]; then
	alias history='history -i' # display formatted history (yyy-mm-dd HH:MM)
elif [[ -n "$BASH_VERSION" ]]; then
	export HISTTIMEFORMAT="%Y-%m-%d %H:%M " # setting this makes 'history' command print the date
fi

# eza package
if command -v eza &>/dev/null; then
	export EZA_COLORS="${EZA_COLORS:-da=1;34:gm=1;34:Su=1;34}"

	alias ls='eza \
	--icons=always \
	--hyperlink=always \
	--group-directories-first \
	--time-style long-iso'

	if eza --git /dev/null &>/dev/null; then
		alias ll='ls -l --git' # Long format, git status
	else
		alias ll='ls -l' # Long format
	fi

	alias l='ll -a'     # Long format, all files
	alias lr='l -T'     # Long format, tree view
	alias ld='ll -d'    # Long format, directories only
	alias lh='ll -d .*' # Long format, hidden files and directories only
	# sorting
	alias lx='l --sort=extension' # Sort by extension
	alias lk='l --sort=size'      # Sort by size (largest last)
	alias lt='l --sort=modified'  # Sort by modified time (newest last)
	alias lc='l --sort=changed'   # Sort by changed time (newest last)
	alias lt='l --sort=type'      # Sort by type (symlink last)
fi

# vscode
if command -v codium-insiders &>/dev/null ||
	command -v codium &>/dev/null; then
	if command -v codium-insiders &>/dev/null; then
		alias code='codium-insiders'
	else
		alias code='codium'
	fi

	alias c.='code .'         # open current directory in new window
	alias cdiff='code --diff' # open two files side by side
	alias cr='code -r'        # open input path in current window
	alias cr.='cr .'          # open current directory in current window
fi

# --- Platform Specific ---

case "$(uname -s)" in
Darwin*)
	alias brewup='brew update && brew upgrade && brew cleanup'

	# Lock the screen (when going AFK)
	alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

	alias wl-copy='pbcopy'
	;;

Linux*)
	alias pbcopy='wl-copy'
	;;

CYGWIN* | MINGW* | MSYS*)
	# Windows / Git Bash
	;;

*) ;;
esac
