function(apply_standard_flags target)
    set(private PRIVATE)
    set(public PUBLIC)
    get_target_property(TYPE "${target}" TYPE)
    if(TYPE STREQUAL "INTERFACE_LIBRARY")
        set(private INTERFACE)
        set(public INTERFACE)
    endif()

    target_compile_options(${target} ${public} -freflection -std=c++26)
endfunction()
