cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED CMAKE_POSITION_INDEPENDENT_CODE)
    # We default to ON for all targets, so that we can use the library in shared libraries.
    set_target_properties(${PROJECT_NAME}-core PROPERTIES INTERFACE_POSITION_INDEPENDENT_CODE ON)
endif()

function(apply_sanitizer_flags)
    if(DOTFILES_SANITIZE_ADDRESS)
        message(STATUS "Setting the address sanitizer sanitizer")
        target_compile_options(${PROJECT_NAME}-core INTERFACE -fsanitize=address -fno-omit-frame-pointer)
        target_libraries(${PROJECT_NAME}-core INTERFACE -fsanitize=address -fno-omit-frame-pointer)
    endif()
    if(DOTFILES_SANITIZE_UNDEFINED)
        message(STATUS "Setting the undefined sanitizer")
        target_compile_options(${PROJECT_NAME}-core INTERFACE -fsanitize=undefined -fno-sanitize-recover=all)
        target_link_options(${PROJECT_NAME}-core INTERFACE -fsanitize=undefined -fno-sanitize-recover=all)
    endif()
    if(DOTFILES_SANITIZE_THREAD)
        message(STATUS "Setting the thread sanitizer")
        target_compile_options(${PROJECT_NAME}-core INTERFACE -fsanitize=thread)
        target_link_options(${PROJECT_NAME}-core INTERFACE -fsanitize=thread)
    endif()
    if(DOTFILES_SANITIZE_MEMORY)
        message(STATUS "Setting the memory sanitizer")
        target_compile_options(${PROJECT_NAME}-core INTERFACE -fsanitize=memory -fno-sanitize-recover=all)
        target_libraries(${PROJECT_NAME}-core INTERFACE -fsanitize=memory -fno-sanitize-recover=all)
    endif()
    # Ubuntu bug for GCC 5.0+ (safe for all versions)
    if(CMAKE_COMPILER_IS_GNUCC)
        target_link_libraries(${PROJECT_NAME}-core INTERFACE -fuse-ld=gold)
    endif()
endfunction()
